In [1]:
import Genotypes

Please stand by. Processing the VCF files might take a while, depending on their size.
Processing Chr21_tr
Processing Chr20_tr
Processing Chr22_tr
---Processing 3 VCFs took 0.09705016613006592 minutes ---
       FID  rs2294895_C  rs6137194_C  rs6060566_C  rs415667_A  rs35693261_T  \
0  HG00096            0            2            0           1             0
1  HG00097            0            0            0           2             0
2  HG00099            0            1            1           0             0
3  HG00100            0            1            1           1             0
4  HG00101            0            1            0           0             0

   rs11911934_A  rs2154490_A  rs4817788_T  rs57137919_A     ...       \
0             0            0            0             0     ...
1             0            0            0             0     ...
2             0            1            2             0     ...
3             0            0            0             0     ...
4             0            0            1             0     ...

   rs59371099_A  rs740223_A  rs5749088_T  rs3205187_G  rs713685_T  \
0             2           0            0            0           0
1             0           1            1            2           0
2             0           0            0            2           0
3             0           2            2            0           1
4             0           0            0            1           0

   rs6518799_A  rs743751_G  rs61741884_T  rs855791_A  rs8135665_T
0            0           0             1           1            2
1            0           0             0           0            1
2            0           0             1           1            0
3            0           0             1           2            0
4            0           0             0           1            0

[5 rows x 25 columns]
The rsID-specific genotypes of your cohort are now saved at Outputs/Genotypes.csv

In [2]:
import pandas as pd

In [5]:
pd.read_csv("./../Outputs/Genotypes.csv", sep="\t", index_col=0).head()

,FID,rs2294895_C,rs6137194_C,rs6060566_C,rs415667_A,rs35693261_T,rs11911934_A,rs2154490_A,rs4817788_T,rs57137919_A,...,rs59371099_A,rs740223_A,rs5749088_T,rs3205187_G,rs713685_T,rs6518799_A,rs743751_G,rs61741884_T,rs855791_A,rs8135665_T
0,HG00096,0,2,0,1,0,0,0,0,0,...,2,0,0,0,0,0,0,1,1,2
1,HG00097,0,0,0,2,0,0,0,0,0,...,0,1,1,2,0,0,0,0,0,1
2,HG00099,0,1,1,0,0,0,1,2,0,...,0,0,0,2,0,0,0,1,1,0
3,HG00100,0,1,1,1,0,0,0,0,0,...,0,2,2,0,1,0,0,1,2,0
4,HG00101,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0